Store CI artifacts (#5)

diff --git a/.github/workflows/check_build.yml b/.github/workflows/check_build.yml
--- a/.github/workflows/check_build.yml
+++ b/.github/workflows/check_build.yml
@@ -16,7 +16,7 @@ env:
 
 jobs:
   kmmTest:
-    runs-on: macos-latest
+    runs-on: ubuntu-20.04
     concurrency:
       group: ${{ github.ref }}_kmmTest
       cancel-in-progress: true
@@ -30,17 +30,31 @@ jobs:
           java-version: ${{ env.JAVA_VERSION }}
       - name: Gradle cache
         uses: gradle/gradle-build-action@v2
+      - name: KMM cache
+        uses: actions/cache@v2
+        id: konan-kmm
+        with:
+          path: '~/.konan/**'
+          key: konan-kmm
       - name: KMM tests
         run: set -o pipefail && ./gradlew --continue testDebugUnitTest
+      # Always run this job even if the previous steps fail to collect all test reports
       - name: Generate KMM test report
         uses: mikepenz/action-junit-report@v3
-        if: always() # Always run even if the previous step fails to collect all reports
+        if: always()
         with:
           report_paths: 'kmm/**/build/test-results/**/TEST-*.xml'
-          check_name: 'KMM Test Report'
+          check_name: 'kmmTestResults'
+      # Always run this job even if the previous steps fail to collect all artifacts
+      - name: Save artifacts
+        uses: actions/upload-artifact@v3
+        if: always()
+        with:
+          name: KMM test results
+          path: 'kmm/**/build/test-results/**/TEST-*.xml'
 
   iosBuild:
-    runs-on: macos-latest
+    runs-on: macos-11
     concurrency:
       group: ${{ github.ref }}_iosBuild
       cancel-in-progress: true
@@ -56,15 +70,29 @@ jobs:
         run: sudo xcode-select -s /Applications/Xcode_${{ env.XCODE_VERSION }}.app
       - name: Gradle cache
         uses: gradle/gradle-build-action@v2
+      - name: KMM cache
+        uses: actions/cache@v2
+        id: konan-ios
+        with:
+          path: '~/.konan/**'
+          key: konan-ios
       - name: Xcode cache
         uses: mikehardy/buildcache-action@v1
       - name: Compile iOS app
         run: |
           cd appIos
-          set -o pipefail && xcodebuild ${{ env.XCODE_CACHE }} -workspace appIos.xcworkspace -scheme "appIos" -sdk iphonesimulator -destination '${{ env.IOS_SIMULATOR }}' build | xcpretty
+          set -o pipefail && xcodebuild ${{ env.XCODE_CACHE }} -workspace appIos.xcworkspace -scheme "appIos" -sdk iphonesimulator -destination '${{ env.IOS_SIMULATOR }}' build | tee xcodebuild.log | xcpretty
+      - name: Save artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          name: iOS build
+          path: |
+            appIos/xcodebuild.log
+            ~/Library/Developer/Xcode/DerivedData/**/Build/Products/**/appIos.app
+            ~/Library/Developer/Xcode/DerivedData/**/Build/Products/**/appIos.app.dSYM
 
   iosTest:
-    runs-on: macos-latest
+    runs-on: macos-11
     concurrency:
       group: ${{ github.ref }}_iosTest
       cancel-in-progress: true
@@ -80,15 +108,27 @@ jobs:
         run: sudo xcode-select -s /Applications/Xcode_${{ env.XCODE_VERSION }}.app
       - name: Gradle cache
         uses: gradle/gradle-build-action@v2
+      - name: KMM cache
+        uses: actions/cache@v2
+        id: konan-ios-test
+        with:
+          path: '~/.konan/**'
+          key: konan-ios-test
       - name: Xcode cache
         uses: mikehardy/buildcache-action@v1
       - name: iOS tests
         run: |
           cd appIos
-          set -o pipefail && xcodebuild ${{ env.XCODE_CACHE }} -workspace appIos.xcworkspace -scheme "appIos" -sdk iphonesimulator -destination '${{ env.IOS_SIMULATOR }}' test | xcpretty
+          set -o pipefail && xcodebuild ${{ env.XCODE_CACHE }} -workspace appIos.xcworkspace -scheme "appIos" -sdk iphonesimulator -destination '${{ env.IOS_SIMULATOR }}' test | tee xcodebuild.log | xcpretty
+      - name: Save artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          name: iOS test results
+          path: |
+            appIos/xcodebuild.log
 
   androidBuild:
-    runs-on: macos-latest
+    runs-on: ubuntu-20.04
     concurrency:
       group: ${{ github.ref }}_androidBuild
       cancel-in-progress: true
@@ -102,11 +142,23 @@ jobs:
           java-version: ${{ env.JAVA_VERSION }}
       - name: Gradle cache
         uses: gradle/gradle-build-action@v2
+      - name: KMM cache
+        uses: actions/cache@v2
+        id: konan-android
+        with:
+          path: '~/.konan/**'
+          key: konan-android
       - name: Compile Android app
         run: set -o pipefail && ./gradlew appAndroid:assembleDebug
+      - name: Save artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          name: Android build
+          path: 'appAndroid/**/build/**/appAndroid-*.apk'
 
   androidTest:
-    runs-on: macos-latest
+    # Needed because of hardware acceleration for the emulator
+    runs-on: macos-11
     concurrency:
       group: ${{ github.ref }}_androidTest
       cancel-in-progress: true
@@ -120,6 +172,12 @@ jobs:
           java-version: ${{ env.JAVA_VERSION }}
       - name: Gradle cache
         uses: gradle/gradle-build-action@v2
+      - name: KMM cache
+        uses: actions/cache@v2
+        id: konan-android-test
+        with:
+          path: '~/.konan/**'
+          key: konan-android-test
       - name: AVD cache
         uses: actions/cache@v2
         id: avd-cache
@@ -147,3 +205,10 @@ jobs:
           emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
           disable-animations: true
           script: set -o pipefail && ./gradlew connectedAndroidTest
+      # Always run this job even if the previous steps fail to collect all artifacts
+      - name: Save artifacts
+        uses: actions/upload-artifact@v3
+        if: always()
+        with:
+          name: Android test results
+          path: 'appAndroid/**/build/outputs/androidTest-results/connected/**/test-result.pb'
